-- MySQL Script generated by MySQL Workbench
-- Thu May  4 09:35:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema comercial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comercial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comercial` DEFAULT CHARACTER SET utf8 ;
USE `comercial` ;

-- -----------------------------------------------------
-- Table `comercial`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comercial`.`users` ;

CREATE TABLE IF NOT EXISTS `comercial`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `pass` VARCHAR(32) NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NULL,
  `admin` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comercial`.`stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comercial`.`stores` ;

CREATE TABLE IF NOT EXISTS `comercial`.`stores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `linx_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comercial`.`users_stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comercial`.`users_stores` ;

CREATE TABLE IF NOT EXISTS `comercial`.`users_stores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_store` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`id_user` ASC) VISIBLE,
  INDEX `store_idx` (`id_store` ASC) VISIBLE,
  CONSTRAINT `users_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `comercial`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `stores_fk`
    FOREIGN KEY (`id_store`)
    REFERENCES `comercial`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
